project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Tomi Capretto"
  site-url: https://tomicapretto.com
  repo-url: https://github.com/tomicapretto/tomicapretto.github.io
  google-analytics: "G-78XRDSRQC8"
  favicon: imgs/mate.png
  navbar:
    background: primary
    right:
      - text: Blog
        href: blog.qmd
      - text: Software
        href: software/index.qmd
      - text: About me
        href: about.qmd
  page-footer:
    center: "Copyright 2026, Tom√°s Capretto"
    background: primary

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
